// Local UI-only preview: no real OBS/process access, installation or capture actions.
const express=require('express'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),app=express();
app.get('/preview',(_req,res)=>res.type('html').send('<!doctype html><meta charset="utf-8"><style>body{font:14px system-ui;background:#dce1e8;color:#415065;margin:32px}iframe{display:block;width:600px;height:420px;border:0;border-radius:12px;margin-top:16px;box-shadow:0 15px 45px #27364b30}label{margin-right:12px}</style><h2>로컬 캡처 · UI 검증</h2><p>실제 OBS·방송을 실행하지 않는 예시입니다. 앱 최소 크기 600 × 420.</p><label for="scenario">상태</label><select id="scenario"><option value="ready">전달 대기</option><option value="fresh">처음 소스 준비</option><option value="clone">클론 후 빌드 전</option><option value="reconnect">OBS 연결 대기</option><option value="live">OBS에 전달 중</option><option value="broadcast">방송 중</option></select><iframe title="로컬 캡처 패널" src="/?scenario=ready"></iframe><script src="/preview-controls.js"></script>'));
app.get('/preview-controls.js',(_req,res)=>res.type('js').send("document.getElementById('scenario').addEventListener('change',event=>{document.querySelector('iframe').src='/?scenario='+event.target.value;});"));
app.get('/',(_req,res)=>res.type('html').send(fs.readFileSync(path.join(root,'index.html'),'utf8').replace('<script src="js/config/constants.js">','<script src="/fixture.js"></script><script src="js/config/constants.js">')));
app.get('/fixture.js',(_req,res)=>res.type('js').send("\nconst scenario=new URLSearchParams(location.search).get('scenario');\nconst state={supported:true,busy:false,ndi:{built:true,processRunning:false,config:{}},\nlocal:{installed:true,registered:true,processRunning:false,running:false,healthy:false,controlAvailable:false,\nrevision:'fixture',configPath:'fixture/local-capture.ini',config:{width:'1920',height:'1080',fps:'30',monitor:'0',buffer_ms:'500',audio_offset_ms:'0'},\nsetup:{built:true,obsInstalled:true,initialized:true,available:true}}};\nif(scenario==='fresh'||scenario==='clone')Object.assign(state.local,{installed:false,registered:false});\nif(scenario==='clone')Object.assign(state.local.setup,{built:false,available:false});\nif(scenario==='reconnect')state.local.processRunning=true;\nif(scenario==='live'||scenario==='broadcast')Object.assign(state.local,{running:true,healthy:true,controlAvailable:true,processRunning:true,sample_rate:48000,audio_peak:.18,width:1920,height:1080,fps:30,send_fps:30,buffer_ms:500,audio_offset_ms:0,captureRequested:true,streaming:scenario==='broadcast'});\nwindow.outputModules={\nstatus:async()=>({ok:true,data:state}),\naction:async action=>{\nif(action==='setup-local')Object.assign(state.local,{installed:true,registered:true});\nif(action==='start-local')Object.assign(state.local,{running:true,healthy:true,controlAvailable:true,processRunning:true,sample_rate:48000,audio_peak:.18,captureRequested:true});\nif(action==='stop-local')Object.assign(state.local,{running:false,captureRequested:false});\nreturn {ok:true,data:{message:'미리보기: '+action}};\n},\nconfigure:async({values})=>{state.local.config={...values};state.local.revision+='x';return {ok:true,data:{message:'예시 설정 저장'}};}\n};\naddEventListener('load',()=>window.deck.run('obs'));\n"));
app.get('/api/status',(_req,res)=>res.json({success:true,status:{chat:{active:false},server:{port:17115}}}));
for(const folder of ['js','css','assets'])app.use('/'+folder,express.static(path.join(root,folder)));
app.get('/icon.svg',(_req,res)=>res.sendFile(path.join(root,'icon.svg')));
app.get('/chat-overlay.html',(_req,res)=>res.sendFile(path.join(root,'src/chat-overlay.html')));
const server=app.listen(17115,'127.0.0.1',()=>console.log('UI fixture: http://127.0.0.1:17115/preview'));
process.on('SIGTERM',()=>server.close(()=>process.exit(0)));
